First homework check
IKromans/home-exercises05-2022-I.K pull request #1
Opened 2022-09-09 17:36 UTC by IKromans

2022-09-15 21:03 UTC, janistumpelis requested changes
Kopumā ir tīri ok, bet nu šur tur ir pāris lietas jāpielabo.

Lai labotu - jāpārslēdzas uz šī pull-request branch, bet pirms pārslēgšanās, ja ir strādāts jau pie jaunā mājadarba - izmaiņas labāk iekomitot (vēl ir variants izmaiņas ielikt stash - par to tad sīkāk jāpalasa, bet tas idejiski ir pagaidu commit).

2022-09-15 21:03 UTC, janistumpelis commented on homeworks052022IK/src/io/codelex/typesandvariables/practice/SadFor.java
> +        return null;
Metodei ir ielikts, ka viņai jāatgriež String, bet tajā pašā laikā metode vienmēr atgriež tikai un vienīgi null. Būtu jāliek metodes return tips kā void un main metodē viņa jāizsauc bez System.out.println

2022-09-16 19:20 UTC, IKromans commented on homeworks052022IK/src/io/codelex/arithmetic/practice/CheckOddEven.java
> +        do {
Jā, šo uzreiz atcerējos, kad nodarbībā stāstīji
check

2022-09-16 19:55 UTC, IKromans commented on homeworks052022IK/src/io/codelex/arithmetic/practice/CalculateArea.java
> +        radius = BigDecimal.valueOf(keyboard.nextDouble());
Jā, kaut kā būšu nepamanījis to. Tagad pieliku klāt, kad liku bija sajūta ka baigi atkārtojas kods. Ātrumā nevarēju izdomāt, bet vai var izveidot vienu pārbaudi visiem variantiem, vai tas tomēr vienalga būs salīdzinoši daudz teksta? ... nu tā kā metodi, kas čeko katru no ievadiem vai ir negatīva un tad attiecīgi izvada attiecīgo skaneri ar Erroru/tekstu.

2022-09-19 10:40 UTC, janistumpelis approved these changes

2022-09-21 15:20 UTC, IKromans commented
first homework merge

2022-09-21 15:21 UTC, merged