Second branch
IKromans/home-exercises05-2022-I.K pull request #7
Opened 2022-10-13 09:15 UTC by IKromans

homework nr.7

2022-10-19 10:37 UTC, janistumpelis requested changes
Nesaprotu vienīgi kāpēc šajā pull-request ir flowcontrol un loops - taisīji zaru no tā branch?

2022-10-19 10:37 UTC, janistumpelis commented on secondhw/src/main/java/io/codelex/streams/practice/StreamsExercise.java
> +    public static int sumAge(List<User> users) {
Te būtu jāiztiek tikai ar streams.
Paskaties ko dara stream iebūvētais mapToInt un kādas darbības pēc tam var veikt ar stream

2022-10-19 10:37 UTC, janistumpelis commented on secondhw/src/main/java/io/codelex/streams/practice/StreamsExercise.java
> +        return new Random().ints(1000000, 2, 30).filter(StreamsExercise::isPrime).sorted().boxed().collect(toList());
Kāpēc te ir Random?

2022-10-19 10:37 UTC, janistumpelis commented on secondhw/src/main/java/io/codelex/streams/practice/StreamsExercise.java
> +        return number > 1 && IntStream.range(2, number).noneMatch(i -> true);
Te izskatās, ka kaut kas nav korekti:
`.noneMatch(i -> true)`

2022-10-19 10:37 UTC, janistumpelis commented on secondhw/src/main/java/io/codelex/streams/practice/StreamsExercise.java
> +    public static List<Integer> generate10RandomNumbers() {
Te izmanto Random, nevis raksti savu algoritmu.

2022-10-19 10:37 UTC, janistumpelis commented on secondhw/src/main/java/io/codelex/streams/practice/StreamsExercise.java
> +    public static User findOldest(List<User> users) {
Te arī izmanto mapToInt - citā komentārā ir paskaidrojums.

2022-10-19 19:12 UTC, IKromans commented
> Nesaprotu vienīgi kāpēc šajā pull-request ir flowcontrol un loops - taisīji zaru no tā branch?

Šim netaisīju jaunu zaru - 2.mājasdarbs bija izlabots un merdžots, izmantoju viņu.

2022-10-30 09:44 UTC, janistumpelis commented
"Šim netaisīju jaunu zaru - 2.mājasdarbs bija izlabots un merdžots, izmantoju viņu." <= vecus zarus nevajag izmantot jauniem darbiem. Katru reizi ir jātaisa jauns branch. Tāpēc arī šajā pull-request parādās vairāk lietas kā vajag, kā arī pašam pēc tam vairāk problēmas rodas.

2022-10-30 09:44 UTC, janistumpelis approved these changes

2022-11-15 22:27 UTC, merged